= New Maven project for FoundationFaces

:hp-tags: JSF, FoundationFaces

The first step to start a new JSF component library is to create the project itself.

I choose the Java Application wizard of Netbeans new project Maven category, I filled the project name `FoundationFaces`, the group id `org.foundation.faces` and I clicked to finish the wizard.

Then I added the `org.glassfish.javax.faces` dependency to my pom.xml:

[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.foundation.faces</groupId>
    <artifactId>FoundationFaces</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <developers>
        <developer>
            <id>hfluz</id>
            <name>Humberto Ferreira da Luz Jr</name>
            <email>hfluz@uel.br</email>
        </developer>
    </developers>
    <dependencies>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.faces</artifactId>
            <version>2.2.12</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>
</project>

In the next step I http://foundation.zurb.com/sites/download.html/[downloaded] the Foundation for Sites resources (CSS, JS and fonts) and put them in this path:

* `src/main/resources/foundation/`
** `css`
*** `foundation.min.css`
*** `foundation-icons.css`
** `fonts`
*** `foundation-icons.eot`
*** `foundation-icons.svg`
*** `foundation-icons.ttf`
*** `foundation-icons.woff`
** `js`
*** `foundation.min.js`
*** `jquery.min.js`

And that's enough to create FoundationFaces first components in the following posts.